version: '3'

services:
  db:
    image: postgres
    container_name: pg-todo-list
    restart: always
    env_file:    
      - .env     
    environment:
      - POSTGRES_DB=${DATABASE}   
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - ./.docker/dbdata:/var/lib/postgresql/data
  
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"  
      - "15672:15672" 
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  app:
    build: .
    container_name: my-nest-app
    restart: always
    depends_on:
      - db
      - rabbitmq
    environment:
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DATABASE=${DATABASE}
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672